### ISSUE TITLE
定制ip时set global include问题

### ISSUE THREAD

**Issue by hiterinbj** [GuoYS0010/hello_e906_zcu104#1]
在package ip时，选择set global include之后，不再报错，但有好多warning，warning信息如下
[IP_Flow 19-5376] File 'd:/a07_e906_zcu/project_1/e906_rtl_factory/gen_rtl/include/tdt_dmi_define.h' is marked as a global include. The packaging process cannot preserve this information, instead the file will be marked as an include file.
大概意思感觉是打包IP的时候就不会作为global include了 
在调用封装好的soc ip连接bd之后，综合时果然出错了，报错的地方就是找不到这些宏定义的东西，
请问下为什么您用这样设置就可以，我准备设置就不可以~是因为vivado版本问题吗？
方便将您的vivado工程传给我参考一下吗

**Comment by GuoYS0010** [comment]
封装成soc之后，再把头文件加入进去试试
![image](https://github.com/user-attachments/assets/419c2a9f-c049-4902-8d4f-213d6da40a6a)

**Comment by GuoYS0010** [comment]
刚更新了，整个工程打包了，放在根目录下。要是之前那个办法不管用的话用我的试试
